name: hoho_hanja
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.10+18

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  dio: ^5.7.0
  crypto: ^3.0.5
  encrypt: ^5.0.3
  convert: ^3.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  sign_in_with_apple: ^6.1.3 # 애플 소셜로그인
  kakao_flutter_sdk: ^1.9.6 # 카카오 소셜로그인
  google_sign_in: ^6.2.1 # 구글 소셜로그인
  hive: ^2.2.3 # 로컬 저장소
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  carousel_slider: ^5.0.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.5
  vector_math: ^2.1.4
  just_audio: ^0.9.41
  flame: ^1.21.0
  volume_controller: ^2.0.8
  path_drawing: ^1.0.1
  font_awesome_flutter: ^10.8.0
  flip_card: ^0.7.0
  change_app_package_name: ^1.4.0
  audio_session: ^0.1.21
  collection: ^1.18.0
  flutter_native_splash: ^2.4.3
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  flutter_launcher_icons: ^0.14.1
  in_app_purchase: ^3.2.0
  marquee: ^2.3.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: "AppIcon"
  image_path_ios: "assets/images/ic_launcher.png"
  image_path_android: "assets/images/ic_launcher.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/social/
    - assets/images/icon/
    - assets/images/bake/
    - assets/images/cookie/
    - assets/images/myroom/
    - assets/lottie/

    - assets/text/

    - assets/audio/bgm/
    - assets/audio/effect/

    - .env

  fonts:
    - family: G-Sans
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
        - asset: assets/fonts/GmarketSansTTFBold.ttf
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: NotoSansKR-Regular
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
    - family: NotoSansKR-SemiBold
      fonts:
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA.ttf
